name: (FREETOWN) Build Docker Image from Tag

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Enter the tag version (e.g., v1.2.3) to build from'
        required: true

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository at specified tag
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: mohmin/${{ github.event.repository.name }}:${{ github.event.inputs.tag }}
